server:
  port: 18080

spring:
  application:
    name: efficient-talk-server
  datasource:
    url: jdbc:mysql://47.122.40.126:3306/efficient_talk
    username: efficient_talk
    password: aIUKaryCc0520.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 50000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false
  servlet:
    # 文件上传配置
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      database: 0
      host: 47.122.40.126
      port: 16379
      password: aIUKaryCc0520.
      timeout: 3000
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 20
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

minio:
  endpoint: http://47.122.40.126:9000
  access-key: admin
  secret-key: 123456789
  org-cloud-disk-bucket: org-cloud-disk
  chat-file-bucket: chat-file
  chat-image-bucket: chat-image
  chat-group-file-bucket: chat-group-file
  chat-group-image-bucket: chat-group-image

mybatis-plus:
#  config-location: classpath:MybatisConfig.xml
#  mapper-locations: classpath:mapper/**.xml
#  check-config-location: true
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.baomidou.mybatisplus: DEBUG
    com.ETGroup.EfficientTalkServer.mapper: DEBUG

knife4j:
  enable: true
  setting:
    language: zh-CN